// Generated by LiveScript 1.5.0
(function(){
  var Links, Nav, UserPref, DotSlash, React, isMoedictDesktop, $body, ref$, p, i, a, b, form, h1, div, main, span, br, h3, h4, button, label, table, nav, tr, td, th, input, hr, meta, ul, ol, li, ruby, small, any, map, createClass, withProperties, divInline, h1Name, rCjkOne, rCjkG, nbsp, CurrentId, Result, Term, HASHOF, XREFLABELOF, XRefs, Star, Heteronym, DefinitionList, Definition, RadicalGlyph, RadicalTable, List, httpMap, http, untag, groupBy, Consonants, Vowels, Tones, re, C, V, keyMap, decodeLangPart, PinYinMap, slice$ = [].slice, replace$ = ''.replace, join$ = [].join, split$ = ''.split, this$ = this;
  Links = require('./scripts/Links.jsx');
  Nav = require('./scripts/Nav.jsx');
  UserPref = require('./scripts/UserPref.jsx');
  DotSlash = !(typeof document != 'undefined' && document !== null) || /^https?:/.exec(typeof document != 'undefined' && document !== null ? document.URL : void 8) ? "./" : "";
  React = require('react');
  if ((typeof window != 'undefined' && window !== null) && window.moedictDesktop) {
    window.isMoedictDesktop = isMoedictDesktop = true;
  }
  $body = (typeof window != 'undefined' && window !== null ? window.$('body') : void 8) || {
    hasClass: function(){
      return false;
    }
  };
  ref$ = React.DOM, p = ref$.p, i = ref$.i, a = ref$.a, b = ref$.b, form = ref$.form, h1 = ref$.h1, div = ref$.div, main = ref$.main, span = ref$.span, br = ref$.br, h3 = ref$.h3, h4 = ref$.h4, button = ref$.button, label = ref$.label, table = ref$.table, nav = ref$.nav, tr = ref$.tr, td = ref$.td, th = ref$.th, input = ref$.input, hr = ref$.hr, meta = ref$.meta, ul = ref$.ul, ol = ref$.ol, li = ref$.li, ruby = ref$.ruby, small = ref$.small;
  ref$ = require('prelude-ls'), any = ref$.any, map = ref$.map;
  createClass = compose$(React.createClass, React.createFactory);
  withProperties = function(tag, defProps){
    defProps == null && (defProps = {});
    return function(props){
      var args, res$, i$, to$;
      props == null && (props = {});
      res$ = [];
      for (i$ = 1, to$ = arguments.length; i$ < to$; ++i$) {
        res$.push(arguments[i$]);
      }
      args = res$;
      return tag.apply(null, [import$(import$({}, defProps), props)].concat(slice$.call(args)));
    };
  };
  divInline = withProperties(div, {
    style: {
      display: 'inline'
    }
  });
  h1Name = withProperties(h1, {
    itemProp: 'name'
  });
  rCjkOne = /^(?:[\uD800-\uDBFF][\uDC00-\uDFFF]|[^？，、；。－—<>])$/;
  rCjkG = /([\uD800-\uDBFF][\uDC00-\uDFFF]|[^？，、；。－—<>])/g;
  nbsp = '\u00A0';
  CurrentId = null;
  Result = createClass({
    render: function(){
      var ref$;
      switch ((ref$ = this.props) != null && ref$.type) {
      case 'term':
        return Term(this.props);
      case 'list':
        return List(this.props);
      case 'radical':
        return RadicalTable(this.props);
      case 'spin':
        return divInline({
          id: 'loading',
          style: {
            marginTop: '19px',
            marginLeft: '1px'
          }
        }, h1({}, this.props.id));
      case 'html':
        return divInline({
          dangerouslySetInnerHTML: {
            __html: this.props.html
          }
        });
      default:
        return div({});
      }
    }
  });
  Term = createClass({
    render: function(){
      var ref$, LANG, H, ref1$, title, english, heteronyms, radical, nrsCount, sCount, py, xrefs, tag, stem, $char, list, res$, i$, len$, key, props;
      ref$ = this.props, LANG = ref$.LANG, H = (ref1$ = ref$.H) != null
        ? ref1$
        : HASHOF[LANG], title = ref$.title, english = ref$.english, heteronyms = ref$.heteronyms, radical = ref$.radical, py = ref$.pinyin, xrefs = ref$.xrefs, tag = ref$.tag, stem = ref$.stem;
      H = replace$.call(H, /^#/, '');
      H = DotSlash + "#" + H;
      CurrentId = this.props.id;
      res$ = [];
      for (i$ = 0, len$ = heteronyms.length; i$ < len$; ++i$) {
        key = i$;
        props = heteronyms[i$];
        res$.push(Heteronym(import$({
          key: key,
          H: H,
          LANG: LANG,
          title: title,
          py: py,
          english: english,
          CurrentId: CurrentId,
          stem: stem
        }, props)));
      }
      list = res$;
      if (xrefs != null && xrefs.length) {
        list = list.concat(XRefs({
          LANG: LANG,
          xrefs: xrefs
        }));
      }
      return divInline.apply(null, [{}].concat(slice$.call(list)));
    }
  });
  HASHOF = {
    p: '#~',
    m: "#!",
    s: '#:'
  };
  XREFLABELOF = {
    p: '方',
    m: '潘',
    s: '蔡'
  };
  XRefs = createClass({
    render: function(){
      var ref$, LANG, xrefs, lang, words, H, word;
      ref$ = this.props, LANG = ref$.LANG, xrefs = ref$.xrefs;
      return div.apply(null, [{
        className: 'xrefs'
      }].concat((function(){
        var i$, ref$, len$, ref1$, results$ = [];
        for (i$ = 0, len$ = (ref$ = xrefs).length; i$ < len$; ++i$) {
          ref1$ = ref$[i$], lang = ref1$.lang, words = ref1$.words;
          H = DotSlash + "" + HASHOF[lang];
          results$.push(div({
            key: lang,
            className: 'xref-line'
          }, span({
            className: 'xref part-of-speech',
            style: {
              marginRight: '5px'
            }
          }, XREFLABELOF[LANG + "" + lang] || XREFLABELOF[lang]), span.apply(null, [{
            className: 'xref',
            itemProp: 'citation'
          }].concat(slice$.call(intersperse('、', (fn$())))))));
        }
        return results$;
        function fn$(){
          var i$, ref$, len$, results$ = [];
          for (i$ = 0, len$ = (ref$ = words).length; i$ < len$; ++i$) {
            word = ref$[i$];
            word = replace$.call(word, /[`~]/g, '');
            results$.push(a({
              key: word,
              className: 'xref',
              href: H + "" + word
            }, word));
          }
          return results$;
        }
      }())));
    }
  });
  Star = createClass({
    render: function(){
      var ref$, CurrentId, LANG, STARRED;
      ref$ = this.props, CurrentId = ref$.CurrentId, LANG = ref$.LANG;
      STARRED = (typeof window != 'undefined' && window !== null ? window.STARRED : void 8) || {};
      if (STARRED[LANG] && ~STARRED[LANG].indexOf("\"" + CurrentId + "\"")) {
        return i({
          className: "star iconic-color icon-bookmark",
          title: '已加入記錄簿'
        });
      }
      return i({
        className: "star iconic-color icon-bookmark-empty",
        title: '加入字詞記錄簿'
      });
    }
  });
  Heteronym = createClass({
    render: function(){
      var ref$, CurrentId, key, $char, H, LANG, title, english, id, audio_id, ref1$, bopomofo, trs, py, pinyin, definitions, antonyms, synonyms, variants, specific_to, alt, stem, re, pinyinList, t, variant, mp3, __html, titleRuby, youyin, bAlt, pAlt, cnSpecific, list, basename, defs;
      ref$ = this.props, CurrentId = ref$.CurrentId, key = ref$.key, $char = ref$.$char, H = ref$.H, LANG = ref$.LANG, title = ref$.title, english = ref$.english, id = ref$.id, audio_id = (ref1$ = ref$.audio_id) != null ? ref1$ : id, bopomofo = ref$.bopomofo, trs = (ref1$ = ref$.trs) != null ? ref1$ : '', py = ref$.py, pinyin = (ref1$ = ref$.pinyin) != null
        ? ref1$
        : py || trs || '', definitions = (ref1$ = ref$.definitions) != null
        ? ref1$
        : [], antonyms = ref$.antonyms, synonyms = ref$.synonyms, variants = ref$.variants, specific_to = ref$.specific_to, alt = ref$.alt, stem = ref$.stem;
      if (audio_id && LANG === 'h') {
        re = /(.)\u20DE(\S+)/g;
        pinyinList = [];
        while (t = re.exec(pinyin)) {
          variant = " 四海大平安南".indexOf(t[1]);
          mp3 = http("h.moedict.tw/" + variant + "-" + audio_id + ".ogg");
          pinyinList = pinyinList.concat(span({
            className: 'audioBlock'
          }, div({
            className: 'icon-play playAudio part-of-speech'
          }, meta({
            itemProp: 'name',
            content: replace$.call(mp3, /^.*\//, '')
          }), meta({
            itemProp: 'contentURL',
            content: mp3
          }), t[1])));
          __html = t[2].replace(/¹/g, '<sup>1</sup>').replace(/²/g, '<sup>2</sup>').replace(/³/g, '<sup>3</sup>').replace(/⁴/g, '<sup>4</sup>').replace(/⁵/g, '<sup>5</sup>');
          pinyinList = pinyinList.concat(span({
            dangerouslySetInnerHTML: {
              __html: __html
            }
          }));
        }
      }
      t = untag(h(title));
      list = [
        span({ dangerouslySetInnerHTML: { __html: title } })
      ];
      if (stem != null) {
        list = list.concat(small({
          className: 'youyin'
        }, a({
          key: stem,
          className: 'xref',
          href: H + "" + stem
        }, "(詞幹:" + stem + ")")));
      }
      if (youyin) {
        list = list.concat(small({
          className: 'youyin'
        }, youyin));
      }
      mp3 = '';
      if (audio_id) {
        if (LANG === 't' && !(20000 < audio_id && audio_id < 50000)) {
          basename = replace$.call(100000 + Number(audio_id), /^1/, '');
          mp3 = http("t.moedict.tw/" + basename + ".ogg");
        } else if (LANG === 'a') {
          mp3 = http("a.moedict.tw/" + audio_id + ".ogg");
        }
      }
      mp3 = http("服務.意傳.台灣/%E6%96%87%E6%9C%AC%E7%9B%B4%E6%8E%A5%E5%90%88%E6%88%90?%E6%9F%A5%E8%A9%A2%E8%85%94%E5%8F%A3=Pangcah&%E6%9F%A5%E8%A9%A2%E8%AA%9E%E5%8F%A5=" + t);
      if (mp3) {
        list = list.concat(i({
          itemType: 'http://schema.org/AudioObject',
          className: 'icon-play playAudio'
        }, meta({
          itemProp: 'name',
          content: t + ".wav"
        }), meta({
          itemProp: 'contentURL',
          content: mp3
        })));
      }
      if (bAlt) {
        if (/-/.exec(typeof localStorage != 'undefined' && localStorage !== null ? localStorage.getItem("pinyin_" + LANG) : void 8)) {
          list = list.concat(small({
            className: 'alternative'
          }, span({
            className: 'pinyin'
          }, pAlt), span({
            className: 'bopomofo',
            style: {
              margin: 0,
              padding: 0,
              marginTop: '4px'
            }
          }, bAlt), span({
            className: 'pinyin'
          }, convertPinyin(pAlt))));
        } else {
          list = list.concat(small({
            className: 'alternative'
          }, span({
            className: 'pinyin'
          }, convertPinyin(pAlt)), span({
            className: 'bopomofo'
          }, bAlt)));
        }
      }
      if (english) {
        list = list.concat(span({
          lang: 'en',
          className: 'english'
        }, english));
      }
      if (specific_to) {
        list = list.concat(span({
          className: 'specific_to',
          dangerouslySetInnerHTML: {
            __html: h(specific_to)
          }
        }));
      }
      return divInline({}, meta({
        itemProp: 'image',
        content: encodeURIComponent(t) + ".png"
      }), meta({
        itemProp: 'name',
        content: t
      }), (key != null ? key : 0) === 0 ? Star({
        CurrentId: CurrentId,
        LANG: LANG
      }) : void 8, $char, h1.apply(null, [{
        className: 'title',
        'data-title': t
      }].concat(slice$.call(list))), bopomofo || alt || pinyinList ? div({
        className: "bopomofo " + cnSpecific
      }, alt != null ? div({
        lang: 'zh-Hans',
        className: 'cn-specific'
      }, span({
        className: 'xref part-of-speech'
      }, '简'), span({
        className: 'xref'
      }, untag(alt))) : void 8, cnSpecific && pinyin && bopomofo ? small({
        className: 'alternative cn-specific'
      }, span({
        className: 'pinyin'
      }, convertPinyin(pinyin)), span({
        className: 'bopomofo'
      }, bopomofo)) : void 8, pinyinList ? span.apply(null, [{
        className: 'pinyin'
      }].concat(slice$.call(pinyinList))) : void 8) : void 8, div.apply(null, [{
        className: 'entry',
        itemProp: 'articleBody'
      }].concat((function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = groupBy('type', definitions.slice())).length; i$ < len$; ++i$) {
          key = i$;
          defs = ref$[i$];
          results$.push(DefinitionList({
            key: key,
            LANG: LANG,
            H: H,
            defs: defs,
            synonyms: synonyms,
            antonyms: antonyms,
            variants: variants
          }));
        }
        return results$;
      }()))));
    }
  });
  DefinitionList = createClass({
    render: function(){
      var ref$, H, LANG, defs, list, key, t, d;
      ref$ = this.props, H = ref$.H, LANG = ref$.LANG, defs = ref$.defs;
      list = [];
      if ((ref$ = defs[0]) != null && ref$.type) {
        list = list.concat(intersperse(nbsp, (function(){
          var i$, ref$, len$, results$ = [];
          for (i$ = 0, len$ = (ref$ = defs[0].type.split(',')).length; i$ < len$; ++i$) {
            key = i$;
            t = ref$[i$];
            results$.push(span({
              key: key,
              className: 'part-of-speech'
            }, untag(t)));
          }
          return results$;
        }())));
      }
      list = list.concat(ol.apply(null, [{}].concat((function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = defs).length; i$ < len$; ++i$) {
          key = i$;
          d = ref$[i$];
          results$.push(Definition(import$({
            key: key,
            H: H,
            LANG: LANG,
            defs: defs
          }, d)));
        }
        return results$;
      }()))));
      list = list.concat(decorateNyms(this.props));
      return div.apply(null, [{
        className: 'entry-item'
      }].concat(slice$.call(list)));
    }
  });
  function decorateNyms(props){
    var list, key, ref$, val, __html;
    list = [];
    for (key in ref$ = {
      synonyms: '似',
      antonyms: '反',
      variants: '異'
    }) {
      val = ref$[key];
      if (props[key]) {
        list = list.concat(span.apply(null, [
          {
            key: key,
            className: key
          }, span({
            className: 'part-of-speech',
            style: {
              marginRight: '5px'
            }
          }, val)
        ].concat(slice$.call(intersperse('、', (fn$()))))));
      }
    }
    return list;
    function fn$(){
      var i$, ref$, len$, results$ = [];
      for (i$ = 0, len$ = (ref$ = split$.call(props[key], /,+/)).length; i$ < len$; ++i$) {
        __html = ref$[i$];
        results$.push(span({
          dangerouslySetInnerHTML: {
            __html: __html
          }
        }));
      }
      return results$;
    }
  }
  Definition = createClass({
    render: function(it){
      var ref$, LANG, type, def, defs, antonyms, synonyms, $afterDef, isColonDef, defString, list, res$, i$, len$, key, style, wrapper, this$ = this;
      ref$ = this.props, LANG = ref$.LANG, type = ref$.type, def = ref$.def, defs = ref$.defs, antonyms = ref$.antonyms, synonyms = ref$.synonyms;
      if (/∥/.exec(def)) {
        $afterDef = div({
          style: {
            margin: "0 0 22px -44px"
          },
          dangerouslySetInnerHTML: {
            __html: h(replace$.call(def, /^[^∥]+/, ''))
          }
        });
        def = replace$.call(def, /∥.*/, '');
      }
      isColonDef = LANG === 'c' && /[:：]<\/span>$/.exec(def) && !any(function(it){
        return /^\s*\(\d+\)/.exec(it.def);
      }, defs);
      defString = h(expandDef(def)).replace(/([：。」])([\u278A-\u2793\u24eb-\u24f4])/g, '$1\uFFFC$2');
      res$ = [];
      for (i$ = 0, len$ = (ref$ = defString.split('\uFFFC')).length; i$ < len$; ++i$) {
        key = i$;
        it = ref$[i$];
        res$.push(span({
          key: key,
          className: 'def',
          dangerouslySetInnerHTML: {
            __html: h(it)
          }
        }));
      }
      list = res$;
      for (i$ = 0, len$ = (ref$ = ['example', 'quote', 'link']).length; i$ < len$; ++i$) {
        if (this.props[ref$[i$]]) {
          (fn$.call(this, ref$[i$]));
        }
      }
      list = list.concat(decorateNyms(this.props));
      if ($afterDef) {
        list = list.concat($afterDef);
      }
      style = isColonDef
        ? {
          marginLeft: '-28px'
        }
        : {};
      wrapper = /^\s*\(\d+\)/.exec(def) || isColonDef
        ? function(it){
          return it;
        }
        : function(it){
          return li({}, it);
        };
      return wrapper(p.apply(null, [{
        className: 'definition',
        style: style
      }].concat(slice$.call(list))));
      function fn$(key){
        var idx, it, __html, $, title, bopomofo, py, ruby;
        list = list.concat((function(){
          var i$, ref$, len$, results$ = [];
          for (i$ = 0, len$ = (ref$ = this.props[key]).length; i$ < len$; ++i$) {
            idx = i$;
            it = ref$[i$];
            __html = h(it);
            results$.push(span({
              key: key + "." + idx,
              className: key,
              dangerouslySetInnerHTML: {
                __html: __html
              }
            }));
          }
          return results$;
        }.call(this)));
      }
    }
  });
  List = createClass({
    render: function(it){
      var ref$, terms, id, H, LRU, list, btn, re, t;
      ref$ = this.props, terms = ref$.terms, id = ref$.id, H = ref$.H, LRU = ref$.LRU;
      if (!terms) {
        return div({});
      }
      H = replace$.call(H, /^#/, '');
      H = DotSlash + "#" + H;
      id = replace$.call(id, /^[@=]/, '');
      terms = replace$.call(terms, /^[^"]*/, '');
      list = [h1Name({}, id)];
      if (id === '字詞紀錄簿' && !terms) {
        btn = i({
          className: 'icon-bookmark-empty'
        });
        list = list.concat(p({
          className: 'bg-info'
        }, "（請按詞條右方的 ", btn, " 按鈕，即可將字詞加到這裡。）"));
      }
      function strToList(str){
        var re, t, it, results$ = [];
        re = /"([^"]+)"[^"]*/g;
        while (t = re.exec(str)) {
          it = t[1];
          results$.push(span({
            style: {
              clear: 'both',
              display: 'block'
            }
          }, '\u00B7', a({
            href: H + "" + it
          }, it)));
        }
        return results$;
      }
      if (/^";/.exec(terms)) {
        re = /";([^;"]+);([^;"]+)"[^"]*/g;
        list = list.concat(table.apply(null, [
          {}, tr.apply(null, [{}].concat((function(){
            var i$, ref$, len$, results$ = [];
            for (i$ = 0, len$ = (ref$ = ['臺', '陸']).length; i$ < len$; ++i$) {
              it = ref$[i$];
              results$.push(th({
                width: 200
              }, span({
                className: 'part-of-speech'
              }, it)));
            }
            return results$;
          }())))
        ].concat((function(){
          var results$ = [];
          while (t = re.exec(terms)) {
            results$.push(tr.apply(null, [{
              style: {
                borderTop: '1px solid #ccc'
              }
            }].concat((fn$()))));
          }
          return results$;
          function fn$(){
            var i$, ref$, len$, results$ = [];
            for (i$ = 0, len$ = (ref$ = [t[1], t[2]]).length; i$ < len$; ++i$) {
              it = ref$[i$];
              results$.push(td({}, a({
                href: H + "" + it
              }, it)));
            }
            return results$;
          }
        }()))));
      } else {
        list = list.concat(strToList(terms));
      }
      if (id === '字詞紀錄簿' && LRU) {
        re = /"([^"]+)"[^"]*/g;
        list = list.concat((br({}), h3({
          id: 'lru'
        }, '最近查閱過的字詞', input({
          id: 'btn-clear-lru',
          type: 'button',
          className: 'btn-default btn btn-tiny',
          value: '清除',
          style: {
            marginLeft: '10px'
          }
        }))));
        list = list.concat(strToList(LRU));
      }
      return divInline.apply(null, [{}].concat(slice$.call(list)));
    }
  });
  httpMap = {
    a: '203146b5091e8f0aafda-15d41c68795720c6e932125f5ace0c70.ssl.cf1.rackcdn.com',
    h: 'a7ff62cf9d5b13408e72-351edcddf20c69da65316dd74d25951e.ssl.cf1.rackcdn.com',
    t: '1763c5ee9859e0316ed6-db85b55a6a3fbe33f09b9245992383bd.ssl.cf1.rackcdn.com'
  };
  if (isMoedictDesktop) {
    import$(httpMap, window.moedictDesktop.voices);
  }
  http = function(it){
    return "http" + (!isMoedictDesktop || !(it.match(/^([^.]+)\.[^\/]+/)[1] in window.moedictDesktop.voices) ? "s" : "") + "://" + it.replace(/^([^.]+)\.[^\/]+/, function(xs, x){
      return httpMap[x] || xs;
    });
  };
  function h(it){
    var id, res;
    id = CurrentId;
    if (/\uFFF9/.exec(it)) {
      it += '</span></span></span></span>';
    }
    res = it.replace(/[\uFF0E\u2022]/g, '\u00B7').replace(/\u223C/g, '\uFF0D').replace(/\u0358/g, '\u030d').replace(/(.)\u20DD/g, "<span class='regional part-of-speech'>$1</span> ").replace(/(.)\u20DE/g, "</span><span class='part-of-speech'>$1</span><span>").replace(/(.)\u20DF/g, "<span class='specific'>$1</span>").replace(/(.)\u20E3/g, "<span class='variant'>$1</span>").replace(RegExp('<a([^<]+)>' + id + '<\\/a>', 'g'), "<a class='mark'$1>" + id + "</a>").replace(RegExp('(>[^<]*)' + id + '(?!</(?:h1|rb)>)<', 'g'), "$1<b>" + id + "</b><");
    if (typeof $ == 'function' && $('body').hasClass('lang-p')) {
      if (res.indexOf('\uFFF9\uFFFA') >= 0) {
        res = res.replace(/\uFFF9/g, '').replace(/\uFFFA/g, '<span class="amisenglish">').replace(/\uFFFB/g, '</span><br><span class="amismandarin">');
      } else {
        res = res.replace(/\uFFF9/g, '<span class="part-of-speech">例</span>&nbsp;<span class="amisnative">').replace(/\uFFFA/g, '</span><br><span class="amisenglish">').replace(/\uFFFB/g, '</span><br><span class="amismandarin">');
      }
    } else if (typeof $ == 'function' && $('body').hasClass('lang-m')) {
      res = res.replace(/\uFFF9/g, '<span class="example-amis">').replace(/\uFFFB/g, '</span><span class="example-fr">');
    } else if (typeof $ == 'function' && $('body').hasClass('lang-s')) {
      res = res.replace(/\uFFF9\uFFFA\uFFFB/g, '').replace(/\uFFF9/g, '<span class="amisnative">').replace(/\uFFFA/g, '').replace(/\uFFFB/g, '</span><br><span class="amismandarin">');
    }
    ({
      'else': res = res.replace(/\uFFF9/g, "<span class=\"ruby" + ((typeof $ == 'function' && $('body').hasClass('lang-t')) && (typeof localStorage != 'undefined' && localStorage !== null ? localStorage.getItem('pinyin_t') : void 8) === "TL-DT" ? " parallel" : "") + "\"><span class=\"rb\"><span class=\"ruby\"><span class=\"rb\">").replace(/\uFFFA/g, '</span><br><span class="rt trs pinyin">').replace(/\uFFFB$/, '').replace(/\uFFFB/g, '</span></span></span></span><br><span class="rt mandarin">').replace(/<span class="rt mandarin">\s*<\//g, '</').replace(/(<span class="rt trs pinyin")>\s*([^<]+)/g, function(_, pre, trs){
        return "" + pre + " title=\"" + trs2bpmf('t', trs) + "\">" + ((typeof $ == 'function' && $('body').hasClass('lang-t')) && (typeof localStorage != 'undefined' && localStorage !== null ? localStorage.getItem('pinyin_t') : void 8) === "TL-DT" ? "<span class='upper'>" + trs.replace(/-/g, "\u2011") + "</span>" : "");
      })
    });
    return res;
  }
  untag = (function(it){
    return replace$.call(it, /<[^>]*>/g, '');
  });
  groupBy = function(prop, xs){
    var x, pre, y;
    if (xs.length <= 1) {
      return [xs];
    }
    x = xs.shift();
    x[prop] == null && (x[prop] = '');
    pre = [x];
    while (xs.length) {
      y = xs[0];
      y[prop] == null && (y[prop] = '');
      if (x[prop] !== y[prop]) {
        break;
      }
      pre.push(xs.shift());
    }
    if (!xs.length) {
      return [pre];
    }
    return [pre].concat(slice$.call(groupBy(prop, xs)));
  };
  function expandDef(def){
    return def.replace(/^\s*<(\d)>\s*([介代副助動名歎嘆形連]?)/, function(_, num, char){
      return String.fromCharCode(0x327F + parseInt(num)) + "" + (char ? char + "\u20DE" : '');
    }).replace(/<(\d)>/g, function(_, num){
      return String.fromCharCode(0x327F + parseInt(num));
    }).replace(/\{(\d)\}/g, function(_, num){
      return String.fromCharCode(0x2775 + parseInt(num));
    }).replace(/[（(](\d)[)）]/g, function(_, num){
      return String.fromCharCode(0x2789 + parseInt(num)) + ' ';
    }).replace(/\(/g, '（').replace(/\)/g, '）');
  }
  function intersperse(elm, xs){
    var list, i$, len$, x;
    list = [];
    for (i$ = 0, len$ = xs.length; i$ < len$; ++i$) {
      x = xs[i$];
      if (list.length) {
        list.push(elm);
      }
      list.push(x);
    }
    return list;
  }
  Consonants = {
    p: 'ㄅ',
    b: 'ㆠ',
    ph: 'ㄆ',
    m: 'ㄇ',
    t: 'ㄉ',
    th: 'ㄊ',
    n: 'ㄋ',
    l: 'ㄌ',
    k: 'ㄍ',
    g: 'ㆣ',
    kh: 'ㄎ',
    ng: 'ㄫ',
    h: 'ㄏ',
    tsi: 'ㄐ',
    ji: 'ㆢ',
    tshi: 'ㄑ',
    si: 'ㄒ',
    ts: 'ㄗ',
    j: 'ㆡ',
    tsh: 'ㄘ',
    s: 'ㄙ'
  };
  Vowels = {
    a: 'ㄚ',
    an: 'ㄢ',
    ang: 'ㄤ',
    ann: 'ㆩ',
    oo: 'ㆦ',
    onn: 'ㆧ',
    o: 'ㄜ',
    e: 'ㆤ',
    enn: 'ㆥ',
    ai: 'ㄞ',
    ainn: 'ㆮ',
    au: 'ㄠ',
    aunn: 'ㆯ',
    am: 'ㆰ',
    om: 'ㆱ',
    m: 'ㆬ',
    ong: 'ㆲ',
    ng: 'ㆭ',
    i: 'ㄧ',
    inn: 'ㆪ',
    u: 'ㄨ',
    unn: 'ㆫ',
    ing: 'ㄧㄥ',
    'in': 'ㄧㄣ',
    un: 'ㄨㄣ'
  };
  Tones = {
    p: 'ㆴ',
    t: 'ㆵ',
    k: 'ㆶ',
    h: 'ㆷ',
    p$: "ㆴ\u0358",
    t$: "ㆵ\u0358",
    k$: "ㆶ\u0358",
    h$: "ㆷ\u0358",
    "\u0300": '˪',
    "\u0301": 'ˋ',
    "\u0302": 'ˊ',
    "\u0304": '˫',
    "\u030d": '$'
  };
  re = function(it){
    var k;
    return (function(){
      var results$ = [];
      for (k in it) {
        results$.push(k);
      }
      return results$;
    }()).sort(function(x, y){
      return y.length - x.length;
    }).join('|');
  };
  C = re(Consonants);
  V = re(Vowels);
  function trs2bpmf(LANG, trs){
    if (LANG === 'h') {
      return ' ';
    }
    if (LANG === 'a') {
      return trs;
    }
    return trs.replace(/[A-Za-z\u0300-\u030d]+/g, function(it){
      var tone;
      tone = '';
      it = it.toLowerCase();
      it = it.replace(/([\u0300-\u0302\u0304\u030d])/, function(it){
        tone = Tones[it];
        return '';
      });
      it = it.replace(/^(tsh?|[sj])i/, '$1ii');
      it = it.replace(/ok$/, 'ook');
      it = it.replace(RegExp('^(' + C + ')((?:' + V + ')+[ptkh]?)$'), function(){
        return Consonants[arguments[1]] + arguments[2];
      });
      it = it.replace(/[ptkh]$/, function(it){
        tone = Tones[it + tone];
        return '';
      });
      it = it.replace(RegExp('(' + V + ')', 'g'), function(it){
        return Vowels[it];
      });
      return it + (tone || '\uFFFD');
    }).replace(/[- ]/g, '').replace(/\uFFFD/g, ' ').replace(/[.?!,] ?/g, '');
  }
  keyMap = {
    h: '"heteronyms"',
    b: '"bopomofo"',
    p: '"pinyin"',
    d: '"definitions"',
    f: '"def"',
    t: '"title"',
    r: '"radical"',
    e: '"example"',
    l: '"link"',
    s: '"synonyms"',
    a: '"antonyms"',
    q: '"quote"',
    _: '"id"',
    '=': '"audio_id"',
    E: '"english"',
    T: '"trs"',
    A: '"alt"',
    V: '"vernacular"',
    C: '"combined"',
    D: '"dialects"',
    S: '"specific_to"'
  };
  decodeLangPart = function(LANGORH, part){
    var H;
    part == null && (part = '');
    while (/"`辨~\u20DE&nbsp`似~\u20DE"[^}]*},{"f":"([^（]+)[^"]*"/.exec(part)) {
      part = part.replace(/"`辨~\u20DE&nbsp`似~\u20DE"[^}]*},{"f":"([^（]+)[^"]*"/, '"辨\u20DE 似\u20DE $1"');
    }
    part = part.replace(/"`(.)~\u20DE"[^}]*},{"f":"([^（]+)[^"]*"/g, '"$1\u20DE $2"');
    part = part.replace(/"([hbpdcnftrelsaqETAVCDS_=])":/g, function(arg$, k){
      return keyMap[k] + ':';
    });
    H = DotSlash + "" + (HASHOF[LANGORH] || LANGORH);
    part = part.replace(/([「【『（《])`([^~]+)~([。，、；：？！─…．·－」』》〉]+)/g, function(arg$, pre, word, post){
      return "<span class=\\\"punct\\\">" + pre + "<a href=\\\"" + H + word + "\\\">" + word + "</a>" + post + "</span>";
    });
    part = part.replace(/([「【『（《])`([^~]+)~/g, function(arg$, pre, word){
      return "<span class=\\\"punct\\\">" + pre + "<a href=\\\"" + H + word + "\\\">" + word + "</a></span>";
    });
    part = part.replace(/`([^~]+)~([。，、；：？！─…．·－」』》〉]+)/g, function(arg$, word, post){
      return "<span class=\\\"punct\\\"><a href=\\\"" + H + word + "\\\">" + word + "</a>" + post + "</span>";
    });
    part = part.replace(/`([^~]+)~/g, function(arg$, word){
      return "<a href=\\\"" + H + word + "\\\">" + word + "</a>";
    });
    part = part.replace(/([)）])/g, "$1\u200B");
    return part;
  };
  module.exports = {
    UserPref: UserPref,
    Result: Result,
    Nav: Nav,
    Links: Links,
    decodeLangPart: decodeLangPart
  };
  PinYinMap = {
    "WadeGiles": {
      "zha": "cha",
      "cha": "ch'a",
      "zhai": "chai",
      "chai": "ch'ai",
      "zhan": "chan",
      "chan": "ch'an",
      "zhang": "chang",
      "chang": "ch'ang",
      "zhao": "chao",
      "chao": "ch'ao",
      "zhe": "che",
      "che": "ch'e",
      "zhei": "chei",
      "zhen": "chen",
      "chen": "ch'en",
      "zheng": "cheng",
      "cheng": "ch'eng",
      "ji": "chi",
      "qi": "ch'i",
      "jia": "chia",
      "qia": "ch'ia",
      "jiang": "chiang",
      "qiang": "ch'iang",
      "jiao": "chiao",
      "qiao": "ch'iao",
      "jie": "chieh",
      "qie": "ch'ieh",
      "jian": "chien",
      "qian": "ch'ien",
      "zhi": "chih",
      "chi": "ch'ih",
      "jin": "chin",
      "qin": "ch'in",
      "jing": "ching",
      "qing": "ch'ing",
      "jiu": "chiu",
      "qiu": "ch'iu",
      "jiong": "chiung",
      "qiong": "ch'iung",
      "zhuo": "cho",
      "chuo": "ch'o",
      "zhou": "chou",
      "chou": "ch'ou",
      "zhu": "chu",
      "chu": "ch'u",
      "zhua": "chua",
      "chua": "ch'ua",
      "zhuai": "chuai",
      "chuai": "ch'uai",
      "zhuan": "chuan",
      "chuan": "ch'uan",
      "zhuang": "chuang",
      "chuang": "ch'uang",
      "zhui": "chui",
      "chui": "ch'ui",
      "zhun": "chun",
      "chun": "ch'un",
      "zhong": "chung",
      "chong": "ch'ung",
      "ju": "chü",
      "qu": "ch'ü",
      "juan": "chüan",
      "quan": "ch'üan",
      "jue": "chüeh",
      "que": "ch'üeh",
      "jun": "chün",
      "qun": "ch'ün",
      "er": "erh",
      "he": "ho",
      "xi": "hsi",
      "xia": "hsia",
      "xiang": "hsiang",
      "xiao": "hsiao",
      "xie": "hsieh",
      "xian": "hsien",
      "xin": "hsin",
      "xing": "hsing",
      "xiu": "hsiu",
      "xiong": "hsiung",
      "xu": "hsü",
      "xuan": "hsüan",
      "xue": "hsüeh",
      "xun": "hsün",
      "hong": "hung",
      "ran": "jan",
      "rang": "jang",
      "rao": "jao",
      "re": "je",
      "ren": "jen",
      "reng": "jeng",
      "ri": "jih",
      "ruo": "jo",
      "rou": "jou",
      "ru": "ju",
      "ruan": "juan",
      "rui": "jui",
      "run": "jun",
      "rong": "jung",
      "ga": "ka",
      "ka": "k'a",
      "gai": "kai",
      "kai": "k'ai",
      "gan": "kan",
      "kan": "k'an",
      "gang": "kang",
      "kang": "k'ang",
      "gao": "kao",
      "kao": "k'ao",
      "gei": "kei",
      "gen": "ken",
      "ken": "k'en",
      "geng": "keng",
      "keng": "k'eng",
      "ge": "ko",
      "ke": "k'o",
      "gou": "kou",
      "kou": "k'ou",
      "gu": "ku",
      "ku": "k'u",
      "gua": "kua",
      "kua": "k'ua",
      "guai": "kuai",
      "kuai": "k'uai",
      "guan": "kuan",
      "kuan": "k'uan",
      "guang": "kuang",
      "kuang": "k'uang",
      "gui": "kuei",
      "kui": "k'uei",
      "gun": "kun",
      "kun": "k'un",
      "gong": "kung",
      "kong": "k'ung",
      "guo": "kuo",
      "kuo": "k'uo",
      "lie": "lieh",
      "lian": "lien",
      "luo": "lo",
      "long": "lung",
      "lv": "lü",
      "lve": "lüeh",
      "lvn": "lün",
      "mie": "mieh",
      "mian": "mien",
      "nie": "nieh",
      "nian": "nien",
      "nuo": "no",
      "nong": "nung",
      "nv": "nü",
      "nve": "nüeh",
      "ba": "pa",
      "pa": "p'a",
      "bai": "pai",
      "pai": "p'ai",
      "ban": "pan",
      "pan": "p'an",
      "bang": "pang",
      "pang": "p'ang",
      "bao": "pao",
      "pao": "p'ao",
      "bei": "pei",
      "pei": "p'ei",
      "ben": "pen",
      "pen": "p'en",
      "beng": "peng",
      "peng": "p'eng",
      "bi": "pi",
      "pi": "p'i",
      "biao": "piao",
      "piao": "p'iao",
      "bie": "pieh",
      "pie": "p'ieh",
      "bian": "pien",
      "pian": "p'ien",
      "bin": "pin",
      "pin": "p'in",
      "bing": "ping",
      "ping": "p'ing",
      "bo": "po",
      "po": "p'o",
      "pou": "p'ou",
      "bu": "pu",
      "pu": "p'u",
      "shi": "shih",
      "shong": "shung",
      "suo": "so",
      "si": "ssu",
      "song": "sung",
      "da": "ta",
      "ta": "t'a",
      "dai": "tai",
      "tai": "t'ai",
      "dan": "tan",
      "tan": "t'an",
      "dang": "tang",
      "tang": "t'ang",
      "dao": "tao",
      "tao": "t'ao",
      "de": "te",
      "te": "t'e",
      "dei": "tei",
      "den": "ten",
      "deng": "teng",
      "teng": "t'eng",
      "di": "ti",
      "ti": "t'i",
      "diang": "tiang",
      "diao": "tiao",
      "tiao": "t'iao",
      "die": "tieh",
      "tie": "t'ieh",
      "dian": "tien",
      "tian": "t'ien",
      "ding": "ting",
      "ting": "t'ing",
      "diu": "tiu",
      "duo": "to",
      "tuo": "t'o",
      "dou": "tou",
      "tou": "t'ou",
      "za": "tsa",
      "ca": "ts'a",
      "zai": "tsai",
      "cai": "ts'ai",
      "zan": "tsan",
      "can": "ts'an",
      "zang": "tsang",
      "cang": "ts'ang",
      "zao": "tsao",
      "cao": "ts'ao",
      "ze": "tse",
      "ce": "ts'e",
      "zei": "tsei",
      "zen": "tsen",
      "cen": "ts'en",
      "zeng": "tseng",
      "ceng": "ts'eng",
      "zuo": "tso",
      "cuo": "ts'o",
      "zou": "tsou",
      "cou": "ts'ou",
      "zu": "tsu",
      "cu": "ts'u",
      "zuan": "tsuan",
      "cuan": "ts'uan",
      "zui": "tsui",
      "cui": "ts'ui",
      "zun": "tsun",
      "cun": "ts'un",
      "zong": "tsung",
      "cong": "ts'ung",
      "du": "tu",
      "tu": "t'u",
      "duan": "tuan",
      "tuan": "t'uan",
      "dui": "tui",
      "tui": "t'ui",
      "dun": "tun",
      "tun": "t'un",
      "dong": "tung",
      "tong": "t'ung",
      "zi": "tzu",
      "ci": "tz'u",
      "yan": "yen",
      "ye": "yeh",
      "you": "yu",
      "yong": "yung",
      "yu": "yü",
      "yuan": "yüan",
      "yue": "yüeh",
      "yun": "yün"
    },
    "GuoYin": {
      "gui": "guei",
      "zhao": "jau",
      "zuo": "tzuo",
      "niao": "niau",
      "zan": "tzan",
      "zou": "tzou",
      "rong": "rung",
      "tao": "tau",
      "ci": "tsz",
      "zong": "tzung",
      "cuo": "tsuo",
      "ao": "au",
      "qiang": "chiang",
      "miao": "miau",
      "xuan": "shiuan",
      "lv": "liu",
      "chun": "chuen",
      "sun": "suen",
      "shi": "shr",
      "kao": "kau",
      "can": "tsan",
      "diao": "diau",
      "zu": "tzu",
      "qun": "chiun",
      "ca": "tsa",
      "xing": "shing",
      "zun": "tzuen",
      "xian": "shian",
      "diu": "diou",
      "shun": "shuen",
      "kun": "kuen",
      "yao": "yau",
      "kui": "kuei",
      "jiong": "jiung",
      "dui": "duei",
      "hao": "hau",
      "zen": "tzen",
      "xun": "shiun",
      "diang": "-",
      "hui": "huei",
      "cong": "tsung",
      "xie": "shie",
      "ju": "jiu",
      "cou": "tsou",
      "ceng": "tseng",
      "jue": "jiue",
      "zui": "tzuei",
      "nve": "niue",
      "zhuai": "juai",
      "zhuang": "juang",
      "cui": "tsuei",
      "ce": "tse",
      "yong": "yung",
      "xi": "shi",
      "cun": "tsuen",
      "chao": "chau",
      "zhui": "juei",
      "xiu": "shiou",
      "xiao": "shiau",
      "xin": "shin",
      "dong": "dung",
      "qie": "chie",
      "sui": "suei",
      "zhun": "juen",
      "zhai": "jai",
      "xu": "shiu",
      "si": "sz",
      "qu": "chiu",
      "zhen": "jen",
      "shao": "shau",
      "chi": "chr",
      "cang": "tsang",
      "qiu": "chiou",
      "gao": "gau",
      "xiang": "shiang",
      "za": "tza",
      "zang": "tzang",
      "cu": "tsu",
      "hong": "hung",
      "zha": "ja",
      "kong": "kung",
      "bao": "bau",
      "zhua": "jua",
      "nv": "niu",
      "cen": "tsen",
      "dun": "duen",
      "nong": "nung",
      "liu": "liou",
      "zao": "tzau",
      "piao": "piau",
      "xia": "shia",
      "tun": "tuen",
      "rao": "rau",
      "jiao": "jiau",
      "zhang": "jang",
      "cuan": "tsuan",
      "zhuo": "juo",
      "qiao": "chiau",
      "nun": "nuen",
      "niu": "niou",
      "qing": "ching",
      "jiu": "jiou",
      "zhu": "ju",
      "sao": "sau",
      "qi": "chi",
      "zhan": "jan",
      "zheng": "jeng",
      "liao": "liau",
      "juan": "jiuan",
      "zhe": "je",
      "cai": "tsai",
      "tong": "tung",
      "zhuan": "juan",
      "zi": "tz",
      "qia": "chia",
      "lao": "lau",
      "gun": "guen",
      "zhou": "jou",
      "tiao": "tiau",
      "tui": "tuei",
      "gong": "gung",
      "zei": "tzei",
      "rui": "ruei",
      "lve": "liue",
      "ze": "tze",
      "xue": "shiue",
      "chong": "chung",
      "zeng": "tzeng",
      "cao": "tsau",
      "xiong": "shiung",
      "hun": "huen",
      "zai": "tzai",
      "que": "chiue",
      "biao": "biau",
      "zhong": "jung",
      "nao": "nau",
      "zuan": "tzuan",
      "song": "sung",
      "qiong": "chiung",
      "run": "ruen",
      "long": "lung",
      "chui": "chuei",
      "zhi": "jr",
      "pao": "pau",
      "lun": "luen",
      "qian": "chian",
      "dao": "dau",
      "quan": "chiuan",
      "shui": "shuei",
      "miu": "miou",
      "lvan": "liuan",
      "ri": "r",
      "jun": "jiun",
      "mao": "mau",
      "zhei": "jei",
      "qin": "chin"
    },
    "TongYong": {
      "shi": "shih",
      "xuan": "syuan",
      "lv": "lyu",
      "liu": "liou",
      "xia": "sia",
      "zhua": "jhua",
      "qiang": "ciang",
      "nv": "nyu",
      "zha": "jha",
      "ci": "cih",
      "xiang": "siang",
      "qiu": "ciou",
      "chi": "chih",
      "zhao": "jhao",
      "si": "sih",
      "qu": "cyu",
      "gui": "guei",
      "zhen": "jhen",
      "zhou": "jhou",
      "hui": "huei",
      "qia": "cia",
      "feng": "fong",
      "zi": "zih",
      "xun": "syun",
      "dui": "duei",
      "zhuan": "jhuan",
      "jiong": "jyong",
      "kui": "kuei",
      "juan": "jyuan",
      "zhe": "jhe",
      "zhu": "jhu",
      "qi": "ci",
      "zheng": "jheng",
      "zhan": "jhan",
      "diu": "diou",
      "jiu": "jiou",
      "qing": "cing",
      "niu": "niou",
      "xian": "sian",
      "xing": "sing",
      "qiao": "ciao",
      "zhuo": "jhuo",
      "zhang": "jhang",
      "qun": "cyun",
      "que": "cyue",
      "wen": "wun",
      "xiong": "syong",
      "zhuang": "jhuang",
      "cui": "cuei",
      "zhuai": "jhuai",
      "xue": "syue",
      "nve": "nyue",
      "zui": "zuei",
      "lve": "lyue",
      "jue": "jyue",
      "rui": "ruei",
      "xie": "sie",
      "tui": "tuei",
      "ju": "jyu",
      "qin": "cin",
      "zhai": "jhai",
      "zhei": "jhei",
      "xu": "syu",
      "weng": "wong",
      "jun": "jyun",
      "zhun": "jhun",
      "lvan": "lyuan",
      "ri": "rih",
      "sui": "suei",
      "qie": "cie",
      "shui": "shuei",
      "miu": "miou",
      "xin": "sin",
      "quan": "cyuan",
      "qian": "cian",
      "xiu": "siou",
      "xiao": "siao",
      "zhi": "jhih",
      "zhui": "jhuei",
      "chui": "chuei",
      "qiong": "cyong",
      "zhong": "jhong",
      "xi": "si"
    }
  };
  function compose$() {
    var functions = arguments;
    return function() {
      var i, result;
      result = functions[0].apply(this, arguments);
      for (i = 1; i < functions.length; ++i) {
        result = functions[i](result);
      }
      return result;
    };
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
